//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.bigldap.ttech.com/", ConfigurationName="BigLdapUpdate.UpdatePersonWs")]
    public interface UpdatePersonWs {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsResult))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateFIDResponse updateFID(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateFID request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateFIDResponse> updateFIDAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateFID request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsResult))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateMSISDNResponse updateMSISDN(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateMSISDN request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateMSISDNResponse> updateMSISDNAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateMSISDN request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsResult))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwEmailResponse updatePwdwEmail(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwEmail request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwEmailResponse> updatePwdwEmailAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwEmail request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsResult))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateEMAILResponse updateEMAIL(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateEMAIL request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateEMAILResponse> updateEMAILAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateEMAIL request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsResult))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateUSERResponse updateUSER(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateUSER request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateUSERResponse> updateUSERAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateUSER request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsResult))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwMsisdnResponse updatePwdwMsisdn(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwMsisdn request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwMsisdnResponse> updatePwdwMsisdnAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwMsisdn request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.bigldap.ttech.com/")]
    public partial class personResult : wsResult {
        
        private person personField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public person person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
                this.RaisePropertyChanged("person");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.bigldap.ttech.com/")]
    public partial class person : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string authInvalidAttemptField;
        
        private string emailField;
        
        private string fbookIdField;
        
        private string firstNameField;
        
        private string fullNameField;
        
        private string msisdnField;
        
        private string passwordField;
        
        private string surnameField;
        
        private string tcellUserField;
        
        private string uidField;
        
        private uidType uidTypeField;
        
        private bool uidTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string authInvalidAttempt {
            get {
                return this.authInvalidAttemptField;
            }
            set {
                this.authInvalidAttemptField = value;
                this.RaisePropertyChanged("authInvalidAttempt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fbookId {
            get {
                return this.fbookIdField;
            }
            set {
                this.fbookIdField = value;
                this.RaisePropertyChanged("fbookId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("fullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
                this.RaisePropertyChanged("msisdn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string tcellUser {
            get {
                return this.tcellUserField;
            }
            set {
                this.tcellUserField = value;
                this.RaisePropertyChanged("tcellUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
                this.RaisePropertyChanged("uid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public uidType uidType {
            get {
                return this.uidTypeField;
            }
            set {
                this.uidTypeField = value;
                this.RaisePropertyChanged("uidType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool uidTypeSpecified {
            get {
                return this.uidTypeFieldSpecified;
            }
            set {
                this.uidTypeFieldSpecified = value;
                this.RaisePropertyChanged("uidTypeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.bigldap.ttech.com/")]
    public enum uidType {
        
        /// <remarks/>
        MSISDN,
        
        /// <remarks/>
        EMAIL,
        
        /// <remarks/>
        FBOOKID,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(personResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.bigldap.ttech.com/")]
    public partial class wsResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorDescField;
        
        private resultCode resultCodeField;
        
        private bool resultCodeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
                this.RaisePropertyChanged("errorDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public resultCode resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("resultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultCodeSpecified {
            get {
                return this.resultCodeFieldSpecified;
            }
            set {
                this.resultCodeFieldSpecified = value;
                this.RaisePropertyChanged("resultCodeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.bigldap.ttech.com/")]
    public enum resultCode {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        SYSTEM_ERROR,
        
        /// <remarks/>
        PERSON_ALREADY_CREATED,
        
        /// <remarks/>
        PERSON_NOT_FOUND,
        
        /// <remarks/>
        FBOOK_ID_ALREADY_BOUND,
        
        /// <remarks/>
        EMAIL_ALREADY_BOUND,
        
        /// <remarks/>
        PERSON_ALREADY_BOUND,
        
        /// <remarks/>
        VALIDATION_ERR_REQUIRED_PARAMETER_MISSING,
        
        /// <remarks/>
        NOT_AUTHENTICATED,
        
        /// <remarks/>
        ACCOUNT_LOCKED,
        
        /// <remarks/>
        PASSWORD_EXPIRED,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateFID", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class updateFID {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msisdn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fbookId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string newFbookId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appId;
        
        public updateFID() {
        }
        
        public updateFID(string msisdn, string email, string fbookId, string newFbookId, string appId) {
            this.msisdn = msisdn;
            this.email = email;
            this.fbookId = fbookId;
            this.newFbookId = newFbookId;
            this.appId = appId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateFIDResponse", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class updateFIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.personResult @return;
        
        public updateFIDResponse() {
        }
        
        public updateFIDResponse(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.personResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateMSISDN", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class updateMSISDN {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msisdn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fbookId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string newMsisdn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appId;
        
        public updateMSISDN() {
        }
        
        public updateMSISDN(string msisdn, string email, string fbookId, string newMsisdn, string appId) {
            this.msisdn = msisdn;
            this.email = email;
            this.fbookId = fbookId;
            this.newMsisdn = newMsisdn;
            this.appId = appId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateMSISDNResponse", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class updateMSISDNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.personResult @return;
        
        public updateMSISDNResponse() {
        }
        
        public updateMSISDNResponse(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.personResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updatePwdwEmail", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class updatePwdwEmail {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string newPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appId;
        
        public updatePwdwEmail() {
        }
        
        public updatePwdwEmail(string email, string newPassword, string appId) {
            this.email = email;
            this.newPassword = newPassword;
            this.appId = appId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updatePwdwEmailResponse", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class updatePwdwEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.personResult @return;
        
        public updatePwdwEmailResponse() {
        }
        
        public updatePwdwEmailResponse(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.personResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateEMAIL", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class updateEMAIL {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msisdn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fbookId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string newEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appId;
        
        public updateEMAIL() {
        }
        
        public updateEMAIL(string msisdn, string email, string fbookId, string newEmail, string appId) {
            this.msisdn = msisdn;
            this.email = email;
            this.fbookId = fbookId;
            this.newEmail = newEmail;
            this.appId = appId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateEMAILResponse", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class updateEMAILResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.personResult @return;
        
        public updateEMAILResponse() {
        }
        
        public updateEMAILResponse(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.personResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateUSER", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class updateUSER {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msisdn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fbookId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string firstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string surname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appId;
        
        public updateUSER() {
        }
        
        public updateUSER(string msisdn, string email, string fbookId, string firstName, string surname, string appId) {
            this.msisdn = msisdn;
            this.email = email;
            this.fbookId = fbookId;
            this.firstName = firstName;
            this.surname = surname;
            this.appId = appId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateUSERResponse", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class updateUSERResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.personResult @return;
        
        public updateUSERResponse() {
        }
        
        public updateUSERResponse(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.personResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updatePwdwMsisdn", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class updatePwdwMsisdn {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msisdn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string newPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appId;
        
        public updatePwdwMsisdn() {
        }
        
        public updatePwdwMsisdn(string msisdn, string newPassword, string appId) {
            this.msisdn = msisdn;
            this.newPassword = newPassword;
            this.appId = appId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updatePwdwMsisdnResponse", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class updatePwdwMsisdnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.personResult @return;
        
        public updatePwdwMsisdnResponse() {
        }
        
        public updatePwdwMsisdnResponse(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.personResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UpdatePersonWsChannel : TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdatePersonWsClient : System.ServiceModel.ClientBase<TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs>, TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs {
        
        public UpdatePersonWsClient() {
        }
        
        public UpdatePersonWsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdatePersonWsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdatePersonWsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdatePersonWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateFIDResponse TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs.updateFID(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateFID request) {
            return base.Channel.updateFID(request);
        }
        
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.personResult updateFID(string msisdn, string email, string fbookId, string newFbookId, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateFID inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateFID();
            inValue.msisdn = msisdn;
            inValue.email = email;
            inValue.fbookId = fbookId;
            inValue.newFbookId = newFbookId;
            inValue.appId = appId;
            TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateFIDResponse retVal = ((TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs)(this)).updateFID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateFIDResponse> TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs.updateFIDAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateFID request) {
            return base.Channel.updateFIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateFIDResponse> updateFIDAsync(string msisdn, string email, string fbookId, string newFbookId, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateFID inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateFID();
            inValue.msisdn = msisdn;
            inValue.email = email;
            inValue.fbookId = fbookId;
            inValue.newFbookId = newFbookId;
            inValue.appId = appId;
            return ((TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs)(this)).updateFIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateMSISDNResponse TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs.updateMSISDN(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateMSISDN request) {
            return base.Channel.updateMSISDN(request);
        }
        
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.personResult updateMSISDN(string msisdn, string email, string fbookId, string newMsisdn, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateMSISDN inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateMSISDN();
            inValue.msisdn = msisdn;
            inValue.email = email;
            inValue.fbookId = fbookId;
            inValue.newMsisdn = newMsisdn;
            inValue.appId = appId;
            TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateMSISDNResponse retVal = ((TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs)(this)).updateMSISDN(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateMSISDNResponse> TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs.updateMSISDNAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateMSISDN request) {
            return base.Channel.updateMSISDNAsync(request);
        }
        
        public System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateMSISDNResponse> updateMSISDNAsync(string msisdn, string email, string fbookId, string newMsisdn, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateMSISDN inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateMSISDN();
            inValue.msisdn = msisdn;
            inValue.email = email;
            inValue.fbookId = fbookId;
            inValue.newMsisdn = newMsisdn;
            inValue.appId = appId;
            return ((TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs)(this)).updateMSISDNAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwEmailResponse TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs.updatePwdwEmail(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwEmail request) {
            return base.Channel.updatePwdwEmail(request);
        }
        
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.personResult updatePwdwEmail(string email, string newPassword, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwEmail inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwEmail();
            inValue.email = email;
            inValue.newPassword = newPassword;
            inValue.appId = appId;
            TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwEmailResponse retVal = ((TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs)(this)).updatePwdwEmail(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwEmailResponse> TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs.updatePwdwEmailAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwEmail request) {
            return base.Channel.updatePwdwEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwEmailResponse> updatePwdwEmailAsync(string email, string newPassword, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwEmail inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwEmail();
            inValue.email = email;
            inValue.newPassword = newPassword;
            inValue.appId = appId;
            return ((TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs)(this)).updatePwdwEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateEMAILResponse TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs.updateEMAIL(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateEMAIL request) {
            return base.Channel.updateEMAIL(request);
        }
        
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.personResult updateEMAIL(string msisdn, string email, string fbookId, string newEmail, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateEMAIL inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateEMAIL();
            inValue.msisdn = msisdn;
            inValue.email = email;
            inValue.fbookId = fbookId;
            inValue.newEmail = newEmail;
            inValue.appId = appId;
            TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateEMAILResponse retVal = ((TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs)(this)).updateEMAIL(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateEMAILResponse> TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs.updateEMAILAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateEMAIL request) {
            return base.Channel.updateEMAILAsync(request);
        }
        
        public System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateEMAILResponse> updateEMAILAsync(string msisdn, string email, string fbookId, string newEmail, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateEMAIL inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateEMAIL();
            inValue.msisdn = msisdn;
            inValue.email = email;
            inValue.fbookId = fbookId;
            inValue.newEmail = newEmail;
            inValue.appId = appId;
            return ((TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs)(this)).updateEMAILAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateUSERResponse TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs.updateUSER(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateUSER request) {
            return base.Channel.updateUSER(request);
        }
        
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.personResult updateUSER(string msisdn, string email, string fbookId, string firstName, string surname, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateUSER inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateUSER();
            inValue.msisdn = msisdn;
            inValue.email = email;
            inValue.fbookId = fbookId;
            inValue.firstName = firstName;
            inValue.surname = surname;
            inValue.appId = appId;
            TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateUSERResponse retVal = ((TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs)(this)).updateUSER(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateUSERResponse> TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs.updateUSERAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateUSER request) {
            return base.Channel.updateUSERAsync(request);
        }
        
        public System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateUSERResponse> updateUSERAsync(string msisdn, string email, string fbookId, string firstName, string surname, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateUSER inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updateUSER();
            inValue.msisdn = msisdn;
            inValue.email = email;
            inValue.fbookId = fbookId;
            inValue.firstName = firstName;
            inValue.surname = surname;
            inValue.appId = appId;
            return ((TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs)(this)).updateUSERAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwMsisdnResponse TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs.updatePwdwMsisdn(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwMsisdn request) {
            return base.Channel.updatePwdwMsisdn(request);
        }
        
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.personResult updatePwdwMsisdn(string msisdn, string newPassword, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwMsisdn inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwMsisdn();
            inValue.msisdn = msisdn;
            inValue.newPassword = newPassword;
            inValue.appId = appId;
            TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwMsisdnResponse retVal = ((TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs)(this)).updatePwdwMsisdn(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwMsisdnResponse> TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs.updatePwdwMsisdnAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwMsisdn request) {
            return base.Channel.updatePwdwMsisdnAsync(request);
        }
        
        public System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwMsisdnResponse> updatePwdwMsisdnAsync(string msisdn, string newPassword, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwMsisdn inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.updatePwdwMsisdn();
            inValue.msisdn = msisdn;
            inValue.newPassword = newPassword;
            inValue.appId = appId;
            return ((TurkcellFacebookDunyasi.ServiceConnector.BigLdapUpdate.UpdatePersonWs)(this)).updatePwdwMsisdnAsync(inValue);
        }
    }
}
