//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Kendo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Kendo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Kendo", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        internal static string FilterMsgAnd {
            get {
                return ResourceManager.GetString("FilterMsgAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string FilterMsgClear {
            get {
                return ResourceManager.GetString("FilterMsgClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string FilterMsgFilter {
            get {
                return ResourceManager.GetString("FilterMsgFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show items with value that:.
        /// </summary>
        internal static string FilterMsgInfo {
            get {
                return ResourceManager.GetString("FilterMsgInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpublished.
        /// </summary>
        internal static string FilterMsgIsFalse {
            get {
                return ResourceManager.GetString("FilterMsgIsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        internal static string FilterMsgIsTrue {
            get {
                return ResourceManager.GetString("FilterMsgIsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string FilterMsgOr {
            get {
                return ResourceManager.GetString("FilterMsgOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Equal To.
        /// </summary>
        internal static string FilterOpDateIsEqualTo {
            get {
                return ResourceManager.GetString("FilterOpDateIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Greater Than.
        /// </summary>
        internal static string FilterOpDateIsGreaterThan {
            get {
                return ResourceManager.GetString("FilterOpDateIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Greater Than Or Equal To.
        /// </summary>
        internal static string FilterOpDateIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterOpDateIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Less Than.
        /// </summary>
        internal static string FilterOpDateIsLessThan {
            get {
                return ResourceManager.GetString("FilterOpDateIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Less Than Or Equal To.
        /// </summary>
        internal static string FilterOpDateIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterOpDateIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Not Equal To.
        /// </summary>
        internal static string FilterOpDateIsNotEqualTo {
            get {
                return ResourceManager.GetString("FilterOpDateIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Equal To.
        /// </summary>
        internal static string FilterOpNumIsEqualTo {
            get {
                return ResourceManager.GetString("FilterOpNumIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Greater Than.
        /// </summary>
        internal static string FilterOpNumIsGreaterThan {
            get {
                return ResourceManager.GetString("FilterOpNumIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Greater Than Or Equal To.
        /// </summary>
        internal static string FilterOpNumIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterOpNumIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Less Than.
        /// </summary>
        internal static string FilterOpNumIsLessThan {
            get {
                return ResourceManager.GetString("FilterOpNumIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Less Than Or Equal To.
        /// </summary>
        internal static string FilterOpNumIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterOpNumIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Not Equal To.
        /// </summary>
        internal static string FilterOpNumIsNotEqualTo {
            get {
                return ResourceManager.GetString("FilterOpNumIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string FilterOpStrContains {
            get {
                return ResourceManager.GetString("FilterOpStrContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn Not Contain.
        /// </summary>
        internal static string FilterOpStrDoesNotContain {
            get {
                return ResourceManager.GetString("FilterOpStrDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends With.
        /// </summary>
        internal static string FilterOpStrEndsWith {
            get {
                return ResourceManager.GetString("FilterOpStrEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Equal To.
        /// </summary>
        internal static string FilterOpStrIsEqualTo {
            get {
                return ResourceManager.GetString("FilterOpStrIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Not Equal To.
        /// </summary>
        internal static string FilterOpStrIsNotEqualTo {
            get {
                return ResourceManager.GetString("FilterOpStrIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts With.
        /// </summary>
        internal static string FilterOpStrStartsWith {
            get {
                return ResourceManager.GetString("FilterOpStrStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string HtmlEditorBold {
            get {
                return ResourceManager.GetString("HtmlEditorBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert hyperlink.
        /// </summary>
        internal static string HtmlEditorCreateLink {
            get {
                return ResourceManager.GetString("HtmlEditorCreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (inherited font).
        /// </summary>
        internal static string HtmlEditorFontNameInherit {
            get {
                return ResourceManager.GetString("HtmlEditorFontNameInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (inherited size).
        /// </summary>
        internal static string HtmlEditorFontSizeInherit {
            get {
                return ResourceManager.GetString("HtmlEditorFontSizeInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert image.
        /// </summary>
        internal static string HtmlEditorInsertImage {
            get {
                return ResourceManager.GetString("HtmlEditorInsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center text.
        /// </summary>
        internal static string HtmlEditorJustifyCenter {
            get {
                return ResourceManager.GetString("HtmlEditorJustifyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify.
        /// </summary>
        internal static string HtmlEditorJustifyFull {
            get {
                return ResourceManager.GetString("HtmlEditorJustifyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align text left.
        /// </summary>
        internal static string HtmlEditorJustifyLeft {
            get {
                return ResourceManager.GetString("HtmlEditorJustifyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align text right.
        /// </summary>
        internal static string HtmlEditorJustifyRight {
            get {
                return ResourceManager.GetString("HtmlEditorJustifyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikethrough.
        /// </summary>
        internal static string HtmlEditorStrikethrough {
            get {
                return ResourceManager.GetString("HtmlEditorStrikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        internal static string HtmlEditorUnderline {
            get {
                return ResourceManager.GetString("HtmlEditorUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove link.
        /// </summary>
        internal static string HtmlEditorUnlink {
            get {
                return ResourceManager.GetString("HtmlEditorUnlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} of {2}.
        /// </summary>
        internal static string PagerDisplay {
            get {
                return ResourceManager.GetString("PagerDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items to display.
        /// </summary>
        internal static string PagerEmpty {
            get {
                return ResourceManager.GetString("PagerEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string PagerFirst {
            get {
                return ResourceManager.GetString("PagerFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PagerItemsPerPage {
            get {
                return ResourceManager.GetString("PagerItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string PagerLast {
            get {
                return ResourceManager.GetString("PagerLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string PagerNext {
            get {
                return ResourceManager.GetString("PagerNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of {0}.
        /// </summary>
        internal static string PagerOf {
            get {
                return ResourceManager.GetString("PagerOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page:.
        /// </summary>
        internal static string PagerPage {
            get {
                return ResourceManager.GetString("PagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string PagerPrevious {
            get {
                return ResourceManager.GetString("PagerPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string PagerRefresh {
            get {
                return ResourceManager.GetString("PagerRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        internal static string StatusUploaded {
            get {
                return ResourceManager.GetString("StatusUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        internal static string StatusUploading {
            get {
                return ResourceManager.GetString("StatusUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string UploadCancel {
            get {
                return ResourceManager.GetString("UploadCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop files here to upload....
        /// </summary>
        internal static string UploadDropFiles {
            get {
                return ResourceManager.GetString("UploadDropFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string UploadRemove {
            get {
                return ResourceManager.GetString("UploadRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string UploadRetry {
            get {
                return ResourceManager.GetString("UploadRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string UploadSelect {
            get {
                return ResourceManager.GetString("UploadSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Selected Files.
        /// </summary>
        internal static string UploadSelectedFiles {
            get {
                return ResourceManager.GetString("UploadSelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string UploadStatusFailed {
            get {
                return ResourceManager.GetString("UploadStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla Yüklendi.
        /// </summary>
        internal static string UploadStatusUploaded {
            get {
                return ResourceManager.GetString("UploadStatusUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yükleniyor....
        /// </summary>
        internal static string UploadStatusUploading {
            get {
                return ResourceManager.GetString("UploadStatusUploading", resourceCulture);
            }
        }
    }
}
