//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Notices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Notices", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AN ERROR OCCURRED! Please be sure to make the right choices.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN FAILED!.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no items to show.
        /// </summary>
        internal static string NoItem {
            get {
                return ResourceManager.GetString("NoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talebiniz alınmıştır, SMS ile bilgilendirileceksiniz..
        /// </summary>
        internal static string RequestSuccess {
            get {
                return ResourceManager.GetString("RequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved!.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image has not been uploaded.
        /// </summary>
        internal static string UploadImgErr {
            get {
                return ResourceManager.GetString("UploadImgErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username is already used. Please enter a different username.
        /// </summary>
        internal static string UsernameExist {
            get {
                return ResourceManager.GetString("UsernameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Detail is required.
        /// </summary>
        internal static string ValContentDetailReq {
            get {
                return ResourceManager.GetString("ValContentDetailReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detay içeriğini giriniz.
        /// </summary>
        internal static string ValFaqContentReq {
            get {
                return ResourceManager.GetString("ValFaqContentReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Image.
        /// </summary>
        internal static string ValFileUploadReq {
            get {
                return ResourceManager.GetString("ValFileUploadReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max: 2MB.
        /// </summary>
        internal static string ValFileUploadSize {
            get {
                return ResourceManager.GetString("ValFileUploadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a image.
        /// </summary>
        internal static string ValFileUploadType {
            get {
                return ResourceManager.GetString("ValFileUploadType", resourceCulture);
            }
        }
    }
}
