//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurkcellFacebookDunyasi.Core.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsrcCommon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsrcCommon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TurkcellFacebookDunyasi.Core.App_GlobalResources.rsrcCommon", typeof(rsrcCommon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required.
        /// </summary>
        public static string AddressReq {
            get {
                return ResourceManager.GetString("AddressReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is required.
        /// </summary>
        public static string AmountReq {
            get {
                return ResourceManager.GetString("AmountReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked UserId is required.
        /// </summary>
        public static string BlockedUserIdReq {
            get {
                return ResourceManager.GetString("BlockedUserIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content is required.
        /// </summary>
        public static string ContentReq {
            get {
                return ResourceManager.GetString("ContentReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        public static string DescriptionReq {
            get {
                return ResourceManager.GetString("DescriptionReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Url.
        /// </summary>
        public static string DetailUrl {
            get {
                return ResourceManager.GetString("DetailUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address.
        /// </summary>
        public static string EmailRegEx {
            get {
                return ResourceManager.GetString("EmailRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string FbEmailReq {
            get {
                return ResourceManager.GetString("FbEmailReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fisrt name is required.
        /// </summary>
        public static string FbFirstNameReq {
            get {
                return ResourceManager.GetString("FbFirstNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name is required.
        /// </summary>
        public static string FbFullNameReq {
            get {
                return ResourceManager.GetString("FbFullNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender is required.
        /// </summary>
        public static string FbGenderReq {
            get {
                return ResourceManager.GetString("FbGenderReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID is required.
        /// </summary>
        public static string FbIdReq {
            get {
                return ResourceManager.GetString("FbIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string FbLastNameReq {
            get {
                return ResourceManager.GetString("FbLastNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale is required.
        /// </summary>
        public static string FbLocaleReq {
            get {
                return ResourceManager.GetString("FbLocaleReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo is required.
        /// </summary>
        public static string FbPhotoReq {
            get {
                return ResourceManager.GetString("FbPhotoReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Link is required.
        /// </summary>
        public static string FbProfileLinkReq {
            get {
                return ResourceManager.GetString("FbProfileLinkReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine Name is required.
        /// </summary>
        public static string FileNameReq {
            get {
                return ResourceManager.GetString("FileNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is required.
        /// </summary>
        public static string FirstNameReq {
            get {
                return ResourceManager.GetString("FirstNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Admin (Full Access).
        /// </summary>
        public static string fullAuth {
            get {
                return ResourceManager.GetString("fullAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login Date.
        /// </summary>
        public static string LastLoginDate {
            get {
                return ResourceManager.GetString("LastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is required.
        /// </summary>
        public static string LastNameReq {
            get {
                return ResourceManager.GetString("LastNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifiedBy.
        /// </summary>
        public static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyDate.
        /// </summary>
        public static string ModifyDate {
            get {
                return ResourceManager.GetString("ModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Msisdn is required.
        /// </summary>
        public static string MsisdnReq {
            get {
                return ResourceManager.GetString("MsisdnReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must be a date.
        /// </summary>
        public static string MustBeADate {
            get {
                return ResourceManager.GetString("MustBeADate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White space is not allowed.
        /// </summary>
        public static string NoWhiteSpace {
            get {
                return ResourceManager.GetString("NoWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Characters is required.
        /// </summary>
        public static string NumberCharactersReq {
            get {
                return ResourceManager.GetString("NumberCharactersReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Sms is required.
        /// </summary>
        public static string NumberSmsReq {
            get {
                return ResourceManager.GetString("NumberSmsReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferTypeCode.
        /// </summary>
        public static string OfferTypeCode {
            get {
                return ResourceManager.GetString("OfferTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid number..
        /// </summary>
        public static string OnlyNumber {
            get {
                return ResourceManager.GetString("OnlyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string PasswordReq {
            get {
                return ResourceManager.GetString("PasswordReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone is required.
        /// </summary>
        public static string PhoneReq {
            get {
                return ResourceManager.GetString("PhoneReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value between 2 and 512..
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value between 2 and 150..
        /// </summary>
        public static string StringLength150 {
            get {
                return ResourceManager.GetString("StringLength150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is Required.
        /// </summary>
        public static string TitleReq {
            get {
                return ResourceManager.GetString("TitleReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TL.
        /// </summary>
        public static string TL {
            get {
                return ResourceManager.GetString("TL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TL Despatch Amount.
        /// </summary>
        public static string TLDespatchAmount {
            get {
                return ResourceManager.GetString("TLDespatchAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TL Transfer Amount.
        /// </summary>
        public static string TlTransferAmount {
            get {
                return ResourceManager.GetString("TlTransferAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TL Transfer Amount is required.
        /// </summary>
        public static string TlTransferAmountReq {
            get {
                return ResourceManager.GetString("TlTransferAmountReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToId.
        /// </summary>
        public static string ToId {
            get {
                return ResourceManager.GetString("ToId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Id is required.
        /// </summary>
        public static string ToIdReq {
            get {
                return ResourceManager.GetString("ToIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TL Despatch Amount.
        /// </summary>
        public static string TransferAmount {
            get {
                return ResourceManager.GetString("TransferAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id is required.
        /// </summary>
        public static string UserIdReq {
            get {
                return ResourceManager.GetString("UserIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string UsernameReq {
            get {
                return ResourceManager.GetString("UsernameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Window.
        /// </summary>
        public static string WindowTypeCode {
            get {
                return ResourceManager.GetString("WindowTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Window is required.
        /// </summary>
        public static string WindowTypeCodeReq {
            get {
                return ResourceManager.GetString("WindowTypeCodeReq", resourceCulture);
            }
        }
    }
}
