//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurkcellFacebookDunyasi.ServiceConnector.BigLdap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.bigldap.ttech.com/", ConfigurationName="BigLdap.GetPersonWs")]
    public interface GetPersonWs {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsResult))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2fbResponse msisdn2fb(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2fb request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2fbResponse> msisdn2fbAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2fb request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsResult))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2msisdnResponse fb2msisdn(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2msisdn request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2msisdnResponse> fb2msisdnAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2msisdn request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsResult))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2fbResponse email2fb(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2fb request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2fbResponse> email2fbAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2fb request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsResult))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2emailResponse msisdn2email(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2email request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2emailResponse> msisdn2emailAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2email request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsResult))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdap.getPersonResponse getPerson(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.getPerson request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdap.getPersonResponse> getPersonAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.getPerson request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsResult))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2emailResponse fb2email(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2email request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2emailResponse> fb2emailAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2email request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsResult))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2msisdnResponse email2msisdn(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2msisdn request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2msisdnResponse> email2msisdnAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2msisdn request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.bigldap.ttech.com/")]
    public partial class stringResult : wsResult {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(personResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(stringResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.bigldap.ttech.com/")]
    public partial class wsResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorDescField;
        
        private resultCode resultCodeField;
        
        private bool resultCodeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
                this.RaisePropertyChanged("errorDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public resultCode resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("resultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultCodeSpecified {
            get {
                return this.resultCodeFieldSpecified;
            }
            set {
                this.resultCodeFieldSpecified = value;
                this.RaisePropertyChanged("resultCodeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.bigldap.ttech.com/")]
    public enum resultCode {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        SYSTEM_ERROR,
        
        /// <remarks/>
        PERSON_ALREADY_CREATED,
        
        /// <remarks/>
        PERSON_NOT_FOUND,
        
        /// <remarks/>
        FBOOK_ID_ALREADY_BOUND,
        
        /// <remarks/>
        EMAIL_ALREADY_BOUND,
        
        /// <remarks/>
        PERSON_ALREADY_BOUND,
        
        /// <remarks/>
        VALIDATION_ERR_REQUIRED_PARAMETER_MISSING,
        
        /// <remarks/>
        NOT_AUTHENTICATED,
        
        /// <remarks/>
        ACCOUNT_LOCKED,
        
        /// <remarks/>
        PASSWORD_EXPIRED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.bigldap.ttech.com/")]
    public partial class person : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string authInvalidAttemptField;
        
        private string emailField;
        
        private string fbookIdField;
        
        private string firstNameField;
        
        private string fullNameField;
        
        private string msisdnField;
        
        private string passwordField;
        
        private string surnameField;
        
        private string tcellUserField;
        
        private string uidField;
        
        private uidType uidTypeField;
        
        private bool uidTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string authInvalidAttempt {
            get {
                return this.authInvalidAttemptField;
            }
            set {
                this.authInvalidAttemptField = value;
                this.RaisePropertyChanged("authInvalidAttempt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fbookId {
            get {
                return this.fbookIdField;
            }
            set {
                this.fbookIdField = value;
                this.RaisePropertyChanged("fbookId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("fullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
                this.RaisePropertyChanged("msisdn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string tcellUser {
            get {
                return this.tcellUserField;
            }
            set {
                this.tcellUserField = value;
                this.RaisePropertyChanged("tcellUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
                this.RaisePropertyChanged("uid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public uidType uidType {
            get {
                return this.uidTypeField;
            }
            set {
                this.uidTypeField = value;
                this.RaisePropertyChanged("uidType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool uidTypeSpecified {
            get {
                return this.uidTypeFieldSpecified;
            }
            set {
                this.uidTypeFieldSpecified = value;
                this.RaisePropertyChanged("uidTypeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.bigldap.ttech.com/")]
    public enum uidType {
        
        /// <remarks/>
        MSISDN,
        
        /// <remarks/>
        EMAIL,
        
        /// <remarks/>
        FBOOKID,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.bigldap.ttech.com/")]
    public partial class personResult : wsResult {
        
        private person personField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public person person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
                this.RaisePropertyChanged("person");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="msisdn2fb", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class msisdn2fb {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msisdn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appId;
        
        public msisdn2fb() {
        }
        
        public msisdn2fb(string msisdn, string appId) {
            this.msisdn = msisdn;
            this.appId = appId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="msisdn2fbResponse", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class msisdn2fbResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdap.stringResult @return;
        
        public msisdn2fbResponse() {
        }
        
        public msisdn2fbResponse(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.stringResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fb2msisdn", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class fb2msisdn {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fbookId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appId;
        
        public fb2msisdn() {
        }
        
        public fb2msisdn(string fbookId, string appId) {
            this.fbookId = fbookId;
            this.appId = appId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fb2msisdnResponse", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class fb2msisdnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdap.stringResult @return;
        
        public fb2msisdnResponse() {
        }
        
        public fb2msisdnResponse(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.stringResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="email2fb", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class email2fb {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appId;
        
        public email2fb() {
        }
        
        public email2fb(string email, string appId) {
            this.email = email;
            this.appId = appId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="email2fbResponse", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class email2fbResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdap.stringResult @return;
        
        public email2fbResponse() {
        }
        
        public email2fbResponse(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.stringResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="msisdn2email", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class msisdn2email {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msisdn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appId;
        
        public msisdn2email() {
        }
        
        public msisdn2email(string msisdn, string appId) {
            this.msisdn = msisdn;
            this.appId = appId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="msisdn2emailResponse", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class msisdn2emailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdap.stringResult @return;
        
        public msisdn2emailResponse() {
        }
        
        public msisdn2emailResponse(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.stringResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPerson", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class getPerson {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appId;
        
        public getPerson() {
        }
        
        public getPerson(string uid, string appId) {
            this.uid = uid;
            this.appId = appId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPersonResponse", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class getPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdap.personResult @return;
        
        public getPersonResponse() {
        }
        
        public getPersonResponse(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.personResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fb2email", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class fb2email {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fbookId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appId;
        
        public fb2email() {
        }
        
        public fb2email(string fbookId, string appId) {
            this.fbookId = fbookId;
            this.appId = appId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fb2emailResponse", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class fb2emailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdap.stringResult @return;
        
        public fb2emailResponse() {
        }
        
        public fb2emailResponse(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.stringResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="email2msisdn", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class email2msisdn {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appId;
        
        public email2msisdn() {
        }
        
        public email2msisdn(string email, string appId) {
            this.email = email;
            this.appId = appId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="email2msisdnResponse", WrapperNamespace="http://ws.bigldap.ttech.com/", IsWrapped=true)]
    public partial class email2msisdnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bigldap.ttech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdap.stringResult @return;
        
        public email2msisdnResponse() {
        }
        
        public email2msisdnResponse(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.stringResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetPersonWsChannel : TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPersonWsClient : System.ServiceModel.ClientBase<TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs>, TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs {
        
        public GetPersonWsClient() {
        }
        
        public GetPersonWsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetPersonWsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetPersonWsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetPersonWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2fbResponse TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs.msisdn2fb(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2fb request) {
            return base.Channel.msisdn2fb(request);
        }
        
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdap.stringResult msisdn2fb(string msisdn, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2fb inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2fb();
            inValue.msisdn = msisdn;
            inValue.appId = appId;
            TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2fbResponse retVal = ((TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs)(this)).msisdn2fb(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2fbResponse> TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs.msisdn2fbAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2fb request) {
            return base.Channel.msisdn2fbAsync(request);
        }
        
        public System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2fbResponse> msisdn2fbAsync(string msisdn, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2fb inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2fb();
            inValue.msisdn = msisdn;
            inValue.appId = appId;
            return ((TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs)(this)).msisdn2fbAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2msisdnResponse TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs.fb2msisdn(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2msisdn request) {
            return base.Channel.fb2msisdn(request);
        }
        
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdap.stringResult fb2msisdn(string fbookId, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2msisdn inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2msisdn();
            inValue.fbookId = fbookId;
            inValue.appId = appId;
            TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2msisdnResponse retVal = ((TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs)(this)).fb2msisdn(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2msisdnResponse> TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs.fb2msisdnAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2msisdn request) {
            return base.Channel.fb2msisdnAsync(request);
        }
        
        public System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2msisdnResponse> fb2msisdnAsync(string fbookId, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2msisdn inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2msisdn();
            inValue.fbookId = fbookId;
            inValue.appId = appId;
            return ((TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs)(this)).fb2msisdnAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2fbResponse TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs.email2fb(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2fb request) {
            return base.Channel.email2fb(request);
        }
        
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdap.stringResult email2fb(string email, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2fb inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2fb();
            inValue.email = email;
            inValue.appId = appId;
            TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2fbResponse retVal = ((TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs)(this)).email2fb(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2fbResponse> TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs.email2fbAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2fb request) {
            return base.Channel.email2fbAsync(request);
        }
        
        public System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2fbResponse> email2fbAsync(string email, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2fb inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2fb();
            inValue.email = email;
            inValue.appId = appId;
            return ((TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs)(this)).email2fbAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2emailResponse TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs.msisdn2email(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2email request) {
            return base.Channel.msisdn2email(request);
        }
        
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdap.stringResult msisdn2email(string msisdn, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2email inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2email();
            inValue.msisdn = msisdn;
            inValue.appId = appId;
            TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2emailResponse retVal = ((TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs)(this)).msisdn2email(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2emailResponse> TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs.msisdn2emailAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2email request) {
            return base.Channel.msisdn2emailAsync(request);
        }
        
        public System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2emailResponse> msisdn2emailAsync(string msisdn, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2email inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdap.msisdn2email();
            inValue.msisdn = msisdn;
            inValue.appId = appId;
            return ((TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs)(this)).msisdn2emailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdap.getPersonResponse TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs.getPerson(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.getPerson request) {
            return base.Channel.getPerson(request);
        }
        
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdap.personResult getPerson(string uid, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdap.getPerson inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdap.getPerson();
            inValue.uid = uid;
            inValue.appId = appId;
            TurkcellFacebookDunyasi.ServiceConnector.BigLdap.getPersonResponse retVal = ((TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs)(this)).getPerson(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdap.getPersonResponse> TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs.getPersonAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.getPerson request) {
            return base.Channel.getPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdap.getPersonResponse> getPersonAsync(string uid, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdap.getPerson inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdap.getPerson();
            inValue.uid = uid;
            inValue.appId = appId;
            return ((TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs)(this)).getPersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2emailResponse TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs.fb2email(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2email request) {
            return base.Channel.fb2email(request);
        }
        
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdap.stringResult fb2email(string fbookId, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2email inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2email();
            inValue.fbookId = fbookId;
            inValue.appId = appId;
            TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2emailResponse retVal = ((TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs)(this)).fb2email(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2emailResponse> TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs.fb2emailAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2email request) {
            return base.Channel.fb2emailAsync(request);
        }
        
        public System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2emailResponse> fb2emailAsync(string fbookId, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2email inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdap.fb2email();
            inValue.fbookId = fbookId;
            inValue.appId = appId;
            return ((TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs)(this)).fb2emailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2msisdnResponse TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs.email2msisdn(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2msisdn request) {
            return base.Channel.email2msisdn(request);
        }
        
        public TurkcellFacebookDunyasi.ServiceConnector.BigLdap.stringResult email2msisdn(string email, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2msisdn inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2msisdn();
            inValue.email = email;
            inValue.appId = appId;
            TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2msisdnResponse retVal = ((TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs)(this)).email2msisdn(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2msisdnResponse> TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs.email2msisdnAsync(TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2msisdn request) {
            return base.Channel.email2msisdnAsync(request);
        }
        
        public System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2msisdnResponse> email2msisdnAsync(string email, string appId) {
            TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2msisdn inValue = new TurkcellFacebookDunyasi.ServiceConnector.BigLdap.email2msisdn();
            inValue.email = email;
            inValue.appId = appId;
            return ((TurkcellFacebookDunyasi.ServiceConnector.BigLdap.GetPersonWs)(this)).email2msisdnAsync(inValue);
        }
    }
}
