//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://vav.kartaca.com/XMLSchema/CallService", ConfigurationName="TiklaKonus.CallPort")]
    public interface CallPort {
        
        // CODEGEN: Generating message contract since the operation getRemainingBalance is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getRemainingBalanceResponse getRemainingBalance(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getRemainingBalanceRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getRemainingBalanceResponse> getRemainingBalanceAsync(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getRemainingBalanceRequest1 request);
        
        // CODEGEN: Generating message contract since the operation startCall is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.startCallResponse1 startCall(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.startCallRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.startCallResponse1> startCallAsync(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.startCallRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getCallInformation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCallInformationResponse1 getCallInformation(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCallInformationRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCallInformationResponse1> getCallInformationAsync(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCallInformationRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getCampaignInformation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCampaignInformationResponse1 getCampaignInformation(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCampaignInformationRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCampaignInformationResponse1> getCampaignInformationAsync(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCampaignInformationRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://vav.kartaca.com/XMLSchema/CallService")]
    public partial class getRemainingBalanceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string campaignCodeField;
        
        private string usingCodeField;
        
        private string participantAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string campaignCode {
            get {
                return this.campaignCodeField;
            }
            set {
                this.campaignCodeField = value;
                this.RaisePropertyChanged("campaignCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string usingCode {
            get {
                return this.usingCodeField;
            }
            set {
                this.usingCodeField = value;
                this.RaisePropertyChanged("usingCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string participantA {
            get {
                return this.participantAField;
            }
            set {
                this.participantAField = value;
                this.RaisePropertyChanged("participantA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vav.kartaca.com/XMLSchema/CallService")]
    public partial class balanceItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime startField;
        
        private System.DateTime endField;
        
        private long durationField;
        
        private double priceField;
        
        private long rankField;
        
        private bool partialUseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
                this.RaisePropertyChanged("end");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("duration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long rank {
            get {
                return this.rankField;
            }
            set {
                this.rankField = value;
                this.RaisePropertyChanged("rank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool partialUse {
            get {
                return this.partialUseField;
            }
            set {
                this.partialUseField = value;
                this.RaisePropertyChanged("partialUse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRemainingBalanceRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vav.kartaca.com/XMLSchema/CallService", Order=0)]
        public TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getRemainingBalanceRequest getRemainingBalanceRequest;
        
        public getRemainingBalanceRequest1() {
        }
        
        public getRemainingBalanceRequest1(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getRemainingBalanceRequest getRemainingBalanceRequest) {
            this.getRemainingBalanceRequest = getRemainingBalanceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRemainingBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRemainingBalanceResponse", Namespace="http://vav.kartaca.com/XMLSchema/CallService", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("package", IsNullable=false)]
        public TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.balanceItem[] getRemainingBalanceResponse1;
        
        public getRemainingBalanceResponse() {
        }
        
        public getRemainingBalanceResponse(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.balanceItem[] getRemainingBalanceResponse1) {
            this.getRemainingBalanceResponse1 = getRemainingBalanceResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://vav.kartaca.com/XMLSchema/CallService")]
    public partial class startCallRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string campaignCodeField;
        
        private string usingCodeField;
        
        private string participantAField;
        
        private string participantBField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string campaignCode {
            get {
                return this.campaignCodeField;
            }
            set {
                this.campaignCodeField = value;
                this.RaisePropertyChanged("campaignCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string usingCode {
            get {
                return this.usingCodeField;
            }
            set {
                this.usingCodeField = value;
                this.RaisePropertyChanged("usingCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string participantA {
            get {
                return this.participantAField;
            }
            set {
                this.participantAField = value;
                this.RaisePropertyChanged("participantA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string participantB {
            get {
                return this.participantBField;
            }
            set {
                this.participantBField = value;
                this.RaisePropertyChanged("participantB");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://vav.kartaca.com/XMLSchema/CallService")]
    public partial class startCallResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long callIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long callId {
            get {
                return this.callIdField;
            }
            set {
                this.callIdField = value;
                this.RaisePropertyChanged("callId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class startCallRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vav.kartaca.com/XMLSchema/CallService", Order=0)]
        public TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.startCallRequest startCallRequest;
        
        public startCallRequest1() {
        }
        
        public startCallRequest1(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.startCallRequest startCallRequest) {
            this.startCallRequest = startCallRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class startCallResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vav.kartaca.com/XMLSchema/CallService", Order=0)]
        public TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.startCallResponse startCallResponse;
        
        public startCallResponse1() {
        }
        
        public startCallResponse1(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.startCallResponse startCallResponse) {
            this.startCallResponse = startCallResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://vav.kartaca.com/XMLSchema/CallService")]
    public partial class getCallInformationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long callIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long callId {
            get {
                return this.callIdField;
            }
            set {
                this.callIdField = value;
                this.RaisePropertyChanged("callId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://vav.kartaca.com/XMLSchema/CallService")]
    public partial class getCallInformationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long callIdField;
        
        private string campaignCodeField;
        
        private string participantAField;
        
        private participantStatus participantStatusAField;
        
        private string participantBField;
        
        private participantStatus participantStatusBField;
        
        private callStatus statusField;
        
        private System.DateTime requestTimeField;
        
        private string usingCodeField;
        
        private long durationField;
        
        private bool durationFieldSpecified;
        
        private double priceField;
        
        private bool priceFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long callId {
            get {
                return this.callIdField;
            }
            set {
                this.callIdField = value;
                this.RaisePropertyChanged("callId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string campaignCode {
            get {
                return this.campaignCodeField;
            }
            set {
                this.campaignCodeField = value;
                this.RaisePropertyChanged("campaignCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string participantA {
            get {
                return this.participantAField;
            }
            set {
                this.participantAField = value;
                this.RaisePropertyChanged("participantA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public participantStatus participantStatusA {
            get {
                return this.participantStatusAField;
            }
            set {
                this.participantStatusAField = value;
                this.RaisePropertyChanged("participantStatusA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string participantB {
            get {
                return this.participantBField;
            }
            set {
                this.participantBField = value;
                this.RaisePropertyChanged("participantB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public participantStatus participantStatusB {
            get {
                return this.participantStatusBField;
            }
            set {
                this.participantStatusBField = value;
                this.RaisePropertyChanged("participantStatusB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public callStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime requestTime {
            get {
                return this.requestTimeField;
            }
            set {
                this.requestTimeField = value;
                this.RaisePropertyChanged("requestTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string usingCode {
            get {
                return this.usingCodeField;
            }
            set {
                this.usingCodeField = value;
                this.RaisePropertyChanged("usingCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public long duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("duration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool durationSpecified {
            get {
                return this.durationFieldSpecified;
            }
            set {
                this.durationFieldSpecified = value;
                this.RaisePropertyChanged("durationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
                this.RaisePropertyChanged("priceSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vav.kartaca.com/XMLSchema/CallService")]
    public enum participantStatus {
        
        /// <remarks/>
        UNKNOWN,
        
        /// <remarks/>
        BUSY,
        
        /// <remarks/>
        ANSWER,
        
        /// <remarks/>
        CALLED_NUMBER,
        
        /// <remarks/>
        NOT_REACHABLE,
        
        /// <remarks/>
        NO_ANSWER,
        
        /// <remarks/>
        DISCONNECTED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vav.kartaca.com/XMLSchema/CallService")]
    public enum callStatus {
        
        /// <remarks/>
        INITIALIZING,
        
        /// <remarks/>
        DIALING_A,
        
        /// <remarks/>
        DIALING_B,
        
        /// <remarks/>
        LIVE,
        
        /// <remarks/>
        CLOSED,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCallInformationRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vav.kartaca.com/XMLSchema/CallService", Order=0)]
        public TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCallInformationRequest getCallInformationRequest;
        
        public getCallInformationRequest1() {
        }
        
        public getCallInformationRequest1(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCallInformationRequest getCallInformationRequest) {
            this.getCallInformationRequest = getCallInformationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCallInformationResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vav.kartaca.com/XMLSchema/CallService", Order=0)]
        public TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCallInformationResponse getCallInformationResponse;
        
        public getCallInformationResponse1() {
        }
        
        public getCallInformationResponse1(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCallInformationResponse getCallInformationResponse) {
            this.getCallInformationResponse = getCallInformationResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://vav.kartaca.com/XMLSchema/CallService")]
    public partial class getCampaignInformationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string campaignCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string campaignCode {
            get {
                return this.campaignCodeField;
            }
            set {
                this.campaignCodeField = value;
                this.RaisePropertyChanged("campaignCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://vav.kartaca.com/XMLSchema/CallService")]
    public partial class getCampaignInformationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private scenario scenarioField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private double minuteLimitField;
        
        private bool minuteLimitFieldSpecified;
        
        private double spentMinutesField;
        
        private bool spentMinutesFieldSpecified;
        
        private long benefitedUserLimitField;
        
        private bool benefitedUserLimitFieldSpecified;
        
        private long benefitedUsersField;
        
        private bool benefitedUsersFieldSpecified;
        
        private long callLimitField;
        
        private bool callLimitFieldSpecified;
        
        private long callsField;
        
        private bool callsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public scenario scenario {
            get {
                return this.scenarioField;
            }
            set {
                this.scenarioField = value;
                this.RaisePropertyChanged("scenario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double minuteLimit {
            get {
                return this.minuteLimitField;
            }
            set {
                this.minuteLimitField = value;
                this.RaisePropertyChanged("minuteLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minuteLimitSpecified {
            get {
                return this.minuteLimitFieldSpecified;
            }
            set {
                this.minuteLimitFieldSpecified = value;
                this.RaisePropertyChanged("minuteLimitSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double spentMinutes {
            get {
                return this.spentMinutesField;
            }
            set {
                this.spentMinutesField = value;
                this.RaisePropertyChanged("spentMinutes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool spentMinutesSpecified {
            get {
                return this.spentMinutesFieldSpecified;
            }
            set {
                this.spentMinutesFieldSpecified = value;
                this.RaisePropertyChanged("spentMinutesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long benefitedUserLimit {
            get {
                return this.benefitedUserLimitField;
            }
            set {
                this.benefitedUserLimitField = value;
                this.RaisePropertyChanged("benefitedUserLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool benefitedUserLimitSpecified {
            get {
                return this.benefitedUserLimitFieldSpecified;
            }
            set {
                this.benefitedUserLimitFieldSpecified = value;
                this.RaisePropertyChanged("benefitedUserLimitSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long benefitedUsers {
            get {
                return this.benefitedUsersField;
            }
            set {
                this.benefitedUsersField = value;
                this.RaisePropertyChanged("benefitedUsers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool benefitedUsersSpecified {
            get {
                return this.benefitedUsersFieldSpecified;
            }
            set {
                this.benefitedUsersFieldSpecified = value;
                this.RaisePropertyChanged("benefitedUsersSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long callLimit {
            get {
                return this.callLimitField;
            }
            set {
                this.callLimitField = value;
                this.RaisePropertyChanged("callLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool callLimitSpecified {
            get {
                return this.callLimitFieldSpecified;
            }
            set {
                this.callLimitFieldSpecified = value;
                this.RaisePropertyChanged("callLimitSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long calls {
            get {
                return this.callsField;
            }
            set {
                this.callsField = value;
                this.RaisePropertyChanged("calls");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool callsSpecified {
            get {
                return this.callsFieldSpecified;
            }
            set {
                this.callsFieldSpecified = value;
                this.RaisePropertyChanged("callsSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vav.kartaca.com/XMLSchema/CallService")]
    public enum scenario {
        
        /// <remarks/>
        MSISDN_PREREQ,
        
        /// <remarks/>
        CODE_PREREQ,
        
        /// <remarks/>
        MSISDN_COUNT,
        
        /// <remarks/>
        CODE_COUNT,
        
        /// <remarks/>
        MSISDN_MINUTE,
        
        /// <remarks/>
        CODE_MINUTE,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCampaignInformationRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vav.kartaca.com/XMLSchema/CallService", Order=0)]
        public TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCampaignInformationRequest getCampaignInformationRequest;
        
        public getCampaignInformationRequest1() {
        }
        
        public getCampaignInformationRequest1(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCampaignInformationRequest getCampaignInformationRequest) {
            this.getCampaignInformationRequest = getCampaignInformationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCampaignInformationResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://vav.kartaca.com/XMLSchema/CallService", Order=0)]
        public TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCampaignInformationResponse getCampaignInformationResponse;
        
        public getCampaignInformationResponse1() {
        }
        
        public getCampaignInformationResponse1(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCampaignInformationResponse getCampaignInformationResponse) {
            this.getCampaignInformationResponse = getCampaignInformationResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CallPortChannel : TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.CallPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CallPortClient : System.ServiceModel.ClientBase<TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.CallPort>, TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.CallPort {
        
        public CallPortClient() {
        }
        
        public CallPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CallPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CallPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CallPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getRemainingBalanceResponse TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.CallPort.getRemainingBalance(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getRemainingBalanceRequest1 request) {
            return base.Channel.getRemainingBalance(request);
        }
        
        public TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.balanceItem[] getRemainingBalance(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getRemainingBalanceRequest getRemainingBalanceRequest) {
            TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getRemainingBalanceRequest1 inValue = new TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getRemainingBalanceRequest1();
            inValue.getRemainingBalanceRequest = getRemainingBalanceRequest;
            TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getRemainingBalanceResponse retVal = ((TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.CallPort)(this)).getRemainingBalance(inValue);
            return retVal.getRemainingBalanceResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getRemainingBalanceResponse> TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.CallPort.getRemainingBalanceAsync(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getRemainingBalanceRequest1 request) {
            return base.Channel.getRemainingBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getRemainingBalanceResponse> getRemainingBalanceAsync(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getRemainingBalanceRequest getRemainingBalanceRequest) {
            TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getRemainingBalanceRequest1 inValue = new TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getRemainingBalanceRequest1();
            inValue.getRemainingBalanceRequest = getRemainingBalanceRequest;
            return ((TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.CallPort)(this)).getRemainingBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.startCallResponse1 TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.CallPort.startCall(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.startCallRequest1 request) {
            return base.Channel.startCall(request);
        }
        
        public TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.startCallResponse startCall(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.startCallRequest startCallRequest) {
            TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.startCallRequest1 inValue = new TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.startCallRequest1();
            inValue.startCallRequest = startCallRequest;
            TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.startCallResponse1 retVal = ((TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.CallPort)(this)).startCall(inValue);
            return retVal.startCallResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.startCallResponse1> TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.CallPort.startCallAsync(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.startCallRequest1 request) {
            return base.Channel.startCallAsync(request);
        }
        
        public System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.startCallResponse1> startCallAsync(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.startCallRequest startCallRequest) {
            TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.startCallRequest1 inValue = new TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.startCallRequest1();
            inValue.startCallRequest = startCallRequest;
            return ((TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.CallPort)(this)).startCallAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCallInformationResponse1 TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.CallPort.getCallInformation(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCallInformationRequest1 request) {
            return base.Channel.getCallInformation(request);
        }
        
        public TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCallInformationResponse getCallInformation(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCallInformationRequest getCallInformationRequest) {
            TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCallInformationRequest1 inValue = new TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCallInformationRequest1();
            inValue.getCallInformationRequest = getCallInformationRequest;
            TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCallInformationResponse1 retVal = ((TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.CallPort)(this)).getCallInformation(inValue);
            return retVal.getCallInformationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCallInformationResponse1> TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.CallPort.getCallInformationAsync(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCallInformationRequest1 request) {
            return base.Channel.getCallInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCallInformationResponse1> getCallInformationAsync(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCallInformationRequest getCallInformationRequest) {
            TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCallInformationRequest1 inValue = new TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCallInformationRequest1();
            inValue.getCallInformationRequest = getCallInformationRequest;
            return ((TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.CallPort)(this)).getCallInformationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCampaignInformationResponse1 TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.CallPort.getCampaignInformation(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCampaignInformationRequest1 request) {
            return base.Channel.getCampaignInformation(request);
        }
        
        public TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCampaignInformationResponse getCampaignInformation(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCampaignInformationRequest getCampaignInformationRequest) {
            TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCampaignInformationRequest1 inValue = new TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCampaignInformationRequest1();
            inValue.getCampaignInformationRequest = getCampaignInformationRequest;
            TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCampaignInformationResponse1 retVal = ((TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.CallPort)(this)).getCampaignInformation(inValue);
            return retVal.getCampaignInformationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCampaignInformationResponse1> TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.CallPort.getCampaignInformationAsync(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCampaignInformationRequest1 request) {
            return base.Channel.getCampaignInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCampaignInformationResponse1> getCampaignInformationAsync(TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCampaignInformationRequest getCampaignInformationRequest) {
            TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCampaignInformationRequest1 inValue = new TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.getCampaignInformationRequest1();
            inValue.getCampaignInformationRequest = getCampaignInformationRequest;
            return ((TurkcellFacebookDunyasi.ServiceConnector.TiklaKonus.CallPort)(this)).getCampaignInformationAsync(inValue);
        }
    }
}
