//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurkcellFacebookDunyasi.Com.Enums {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsrcEnumDisplays {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsrcEnumDisplays() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TurkcellFacebookDunyasi.Com.Enums.rsrcEnumDisplays", typeof(rsrcEnumDisplays).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string OfferType_General {
            get {
                return ResourceManager.GetString("OfferType_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        public static string OfferType_Startup {
            get {
                return ResourceManager.GetString("OfferType_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion.
        /// </summary>
        public static string OfferType_Suggestion {
            get {
                return ResourceManager.GetString("OfferType_Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _blank.
        /// </summary>
        public static string WindowPosition_blank {
            get {
                return ResourceManager.GetString("WindowPosition_blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _parent.
        /// </summary>
        public static string WindowPosition_parent {
            get {
                return ResourceManager.GetString("WindowPosition_parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _self.
        /// </summary>
        public static string WindowPosition_self {
            get {
                return ResourceManager.GetString("WindowPosition_self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _top.
        /// </summary>
        public static string WindowPosition_top {
            get {
                return ResourceManager.GetString("WindowPosition_top", resourceCulture);
            }
        }
    }
}
